name: Label PRs to allow add-to-project to run

permissions:
  pull-requests: write

on:
  pull_request:
    types: [ labeled ]

jobs:
  add-to-project-label:
    name: Add label after a day
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          days-before-stale: 1
           stale-pr-label: 'sorted'
