name: Label PRs to allow add-to-project to run

permissions:
  pull-requests: write

on:
  schedule:
    - cron: '0 6 * * *'

jobs:
  add-to-project-label:
    name: Add label after a day
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          days-before-stale: 1
          stale-pr-label: 'sorted'
